# Generated by Django 4.2.4 on 2023-08-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='causes_supported',
            field=models.ManyToManyField(related_name='organizations', to='category.category'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='interests',
            field=models.ManyToManyField(related_name='volunteers', to='category.category'),
        ),
    ]
