# Generated by Django 4.2.4 on 2023-08-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_organizationprofile_causes_supported_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organisation',
            new_name='is_organization',
        ),
    ]
