# Generated by Django 4.2.3 on 2023-08-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_badge'),
        ('users', '0003_rename_is_organisation_user_is_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='badges',
            field=models.ManyToManyField(related_name='awarded_volunteers', to='category.badge'),
        ),
    ]
