# Generated by Django 4.2.4 on 2023-08-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_badge'),
        ('users', '0004_volunteerprofile_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='causes_supported',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='category.category'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='category.category'),
        ),
    ]
