# Generated by Django 4.2.4 on 2023-08-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_badge'),
        ('users', '0005_alter_organizationprofile_causes_supported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='awarded_volunteers', to='category.badge'),
        ),
    ]
