# Generated by Django 4.2.3 on 2023-08-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_volunteerprofile_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=99999999),
        ),
    ]
