# Generated by Django 4.2.3 on 2023-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_volunteerprofile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
