# Generated by Django 4.2.4 on 2023-08-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_organizationprofile_causes_supported_and_more'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
