# Generated by Django 4.2.3 on 2023-08-16 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_organizationprofile_causes_supported_and_more'),
        ('posts', '0005_alter_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizationprofile'),
        ),
    ]
