# Generated by Django 4.2.4 on 2023-08-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_volunteerprofile_badges'),
        ('posts', '0008_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organizationprofile'),
        ),
    ]
