# Generated by Django 4.2.3 on 2023-08-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_volunteerprofile_rank'),
        ('posts', '0011_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.organizationprofile'),
        ),
    ]
