# Generated by Django 4.2.3 on 2023-08-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_badge'),
        ('posts', '0012_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_of', to='category.category'),
        ),
    ]
